name: Upload Python Package to PyPI

on:
  push:
    tags:
      - "v*.*.*" # e.g. v0.1.0

permissions:
  contents: read

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # full git history needed for branch ancestry check

      - name: Check if tag commit is on main branch
        run: |
          if ! git branch --contains $GITHUB_SHA | grep -q 'main'; then
            echo "Tag commit is not on main branch. Exiting."
            exit 78
          fi

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip build twine

      - name: Build package
        run: |
          python -m build

      - name: Publish to PyPI
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
        run: |
          twine upload dist/*
